name: pluto_grid_riverpod_example
description: Why does the PlutoGrid not rebuild on stream updates?
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  cloud_firestore: ^4.5.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.10.0
  flutter_riverpod: ^2.3.5
  pluto_grid: ^6.0.4
  riverpod_annotation: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.0
  riverpod_lint: ^1.3.0

flutter:
  uses-material-design: true

